### ISSUE TITLE
P8

### ISSUE THREAD

**Issue by SmirkCao** [yanyan-li/SLAM-BOOK#1]
P8倒数第四行，应该是 “先从直线说起”
另外latex可以用lineno包，书稿可以显示行号，这样方便issue时候说明是在多少行。

加油，有空关注。

**Comment by yanyan-li** [comment]
感谢，已经修改。

**Comment by SmirkCao** [comment]
P8L268 就是“先重直线说起”么？

**Comment by yanyan-li** [comment]
sorry,我理解错了你的意思，这段描述不对，已经重新整理了。感谢。
