### ISSUE TITLE
大部分字错误，小部分格式错误，详情请看图

### ISSUE THREAD

**Issue by uanheng** [yanyan-li/SLAM-BOOK#13]
![536简繁体切换错误](https://user-images.githubusercontent.com/16514555/131770583-62f7f323-cc1a-4652-a672-47232462d2ae.png)
![538代词错误（它）](https://user-images.githubusercontent.com/16514555/131770589-68decf7b-2c85-44a5-b898-c01488372df6.png)
![553缺少波浪号](https://user-images.githubusercontent.com/16514555/131770591-09bccb8c-9295-43a7-97a7-18722e2de231.png)
![579粗体错误](https://user-images.githubusercontent.com/16514555/131770592-16a966de-d253-4a04-a9aa-4a6300bcaa83.png)
![777引用错误](https://user-images.githubusercontent.com/16514555/131770595-63aa3def-09ec-4fe0-bf8b-671bdb735080.png)
![1108字错误（想）](https://user-images.githubusercontent.com/16514555/131770597-8e8dd190-f705-490b-a6df-ee2c6f23c3b1.png)
![1114字错误（路）](https://user-images.githubusercontent.com/16514555/131770600-e69d71e4-4724-4b98-a209-6d25eae72a28.png)
![1119字错误（路）](https://user-images.githubusercontent.com/16514555/131770601-05ebb980-995d-4e0a-a546-d544532d39f9.png)
![1277符号混乱](https://user-images.githubusercontent.com/16514555/131770603-7d34fe1c-5af2-4cee-a8ed-4f169a2ac187.png)
![1508行代码越界](https://user-images.githubusercontent.com/16514555/131770606-2c34fe99-06ce-4339-9142-0379f7441c34.png)

**Comment by yanyan-li** [comment]
Thanks a lot. I will fix those bugs.
