### ISSUE TITLE
内容还会继续补充吗

### ISSUE THREAD

**Issue by liaoksn** [yanyan-li/SLAM-BOOK#15]
作者您好，感谢您整理了相关的信息，关注到第十一章及之后的内容都还有很多空缺，请问您还会继续更新嘛

**Comment by JaySlamer** [comment]
> 作者您好，感谢您整理了相关的信息，关注到第十一章及之后的内容都还有很多空缺，请问您还会继续更新嘛

据我多年的经验，这书早太监了。

**Comment by liaoksn** [comment]
那，请问有相关内容的一些最近的书籍推荐嘛，感谢
&nbsp;


liaok
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月5日(星期一) 下午4:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yanyan-li/SLAM-BOOK] 内容还会继续补充吗 (Issue #15)





  
作者您好，感谢您整理了相关的信息，关注到第十一章及之后的内容都还有很多空缺，请问您还会继续更新嘛
  
据我多年的经验，这书早太监了。

**Comment by JaySlamer** [comment]
> 那，请问有相关内容的一些最近的书籍推荐嘛，感谢 &nbsp; liaok ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年12月5日(星期一) 下午4:53 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [yanyan-li/SLAM-BOOK] 内容还会继续补充吗 (Issue #15) 作者您好，感谢您整理了相关的信息，关注到第十一章及之后的内容都还有很多空缺，请问您还会继续更新嘛 据我多年的经验，这书早太监了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

《视觉slam十四讲》《计算机视觉的多视图几何》《机器人学的状态估计》《概率机器人学》

**Comment by liaoksn** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        hhhhhhh，都是一些比较经典的书籍啊，感谢感谢。看样子最近的东西还得看论文
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年12月5日 16:58
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [yanyan-li/SLAM-BOOK] 内容还会继续补充吗 (Issue #15)
        
      
    
  
  

那，请问有相关内容的一些最近的书籍推荐嘛，感谢   liaok @.***  
…
------------------ 原始邮件 ------------------ 发件人: @.>; 发送时间: 2022年12月5日(星期一) 下午4:53 收件人: @.>; 抄送: @.>; @.>; 主题: Re: [yanyan-li/SLAM-BOOK] 内容还会继续补充吗 (Issue #15) 作者您好，感谢您整理了相关的信息，关注到第十一章及之后的内容都还有很多空缺，请问您还会继续更新嘛 据我多年的经验，这书早太监了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>
《视觉slam十四讲》《计算机视觉的多视图几何》《机器人学的状态估计》《概率机器人学》
