### ISSUE TITLE
部分表达错误

### ISSUE THREAD

**Issue by ouyangandy** [yanyan-li/SLAM-BOOK#2]
为了严谨性，提出一些不太严谨的建议：
1、p3(128-130行)的表达有问题；
2、p26 公式4.2仿佛多了一个s？
3、p28（772-773行）文字表达有误；
4、p29（794行）文字表达有误；

还没看完，会继续看下去......

作者加油！

**Comment by yanyan-li** [comment]
感谢感谢。已经修改了相关内容。
