### ISSUE TITLE
文本中的错误（建议源文本剖分开源）

### ISSUE THREAD

**Issue by zhuyuanxiang** [yanyan-li/SLAM-BOOK#20]
Line240：

- 错：图5
- 对：图1

**Comment by zhuyuanxiang** [comment]
Line251：
- 错：若纹理
- 对：弱纹理

**Comment by zhuyuanxiang** [comment]
Line248：

- 错：很都工作
- 对：很多工作

**Comment by JaySlamer** [comment]
这坟挖的，这书都三年没更新了。作者和读者们都弃坑了。

**Comment by zhuyuanxiang** [comment]
> 这坟挖的，这书都三年没更新了。作者和读者们都弃坑了。
我是希望作者愿意把剖分内容共享出来，这样子后面的人就可以基于这个成果继续更新。

**Comment by zhuyuanxiang** [comment]
Line 350~351：
内容描述可能有误，或者英文注释有误。
