### ISSUE TITLE
The errors in Chapter 0

### ISSUE THREAD

**Issue by DoongLi** [yanyan-li/SLAM-BOOK#21]
![1721156809983](https://github.com/user-attachments/assets/c9245c59-53d0-4a2a-987e-c30620e1d33d)

Chapter 0 line 96&97: spelling error.

**Comment by DoongLi** [comment]
![2](https://github.com/user-attachments/assets/9d6815c8-b439-48f3-8441-f1e66d4dce19)

Chapter 1 line 32: There does not appear to be an expression like '概论模型' in Chinese.

**Comment by DoongLi** [comment]
![1721157598948](https://github.com/user-attachments/assets/fddfe7f5-fb4b-4da2-a8f9-39d20c441969)
Chapter 1 line 34: 'P' should be placed after '地标' and before '的环境中'.

**Comment by DoongLi** [comment]
and the expressions '姿势' and '位姿' should be unified.

**Comment by DoongLi** [comment]
![1](https://github.com/user-attachments/assets/7959b234-37b9-4201-8f62-eb1edbc57ce6)

Chapter 1 line 40: spelling error.
Chapter 1 line 41: repetitive vocabulary.

**Comment by DoongLi** [comment]
![1](https://github.com/user-attachments/assets/884ff491-9141-4af5-bb7c-8ab87d252c90)
Chapter 1 line 48: spelling error.

**Comment by DoongLi** [comment]
![1](https://github.com/user-attachments/assets/208ea1a2-3a36-4a68-a40c-85eaca9845fb)
Chapter 1 line 55: Is the definition of the descriptor“描述符” rigorous enough here?

**Comment by DoongLi** [comment]
![1](https://github.com/user-attachments/assets/dec29516-548c-4a1d-9d6f-be9292d6292b)
Chapter 1 line 58:  you could consider changing 'point(s)' to 'keypoint(s)'.

**Comment by DoongLi** [comment]
![1](https://github.com/user-attachments/assets/52b55d9b-4bee-42b7-bf81-1aa3e37d0cf8)
Chapter 1 line 81&95: spelling error.

**Comment by DoongLi** [comment]
![1](https://github.com/user-attachments/assets/7c80fb86-5c01-4873-890c-388210b6d1ff)
Chapter 1 line 99: improper expression.

**Comment by DoongLi** [comment]
![1](https://github.com/user-attachments/assets/a66ad731-2110-4dc8-9382-e3ae93bc2758)
Chapter 1 line 204: spelling error.

**Comment by DoongLi** [comment]
![1](https://github.com/user-attachments/assets/89fc0b2e-fe35-45cd-92ac-ce488b98d391)
Chapter 1 line 211: improper expression.

**Comment by DoongLi** [comment]
![1](https://github.com/user-attachments/assets/c27fc27c-a434-4a98-b520-e51562ec4a93)
Chapter 1 line 211: SfM-SFM?

**Comment by DoongLi** [comment]
![1](https://github.com/user-attachments/assets/11480093-9afc-4162-84bc-c01be9bff82a)
Chapter 1 line 483&487: spelling error.
Chapter 1 line 486: the expressions 'NeRF' and 'NeRFs' should be unified.

**Comment by DoongLi** [comment]
![1](https://github.com/user-attachments/assets/242edeac-03dd-4c46-9b1c-84601ef91f73)
Chapter 1 line 452: improper expression.

**Comment by DoongLi** [comment]
![1](https://github.com/user-attachments/assets/2ddfd067-8e07-4829-a06a-128d824ad550)
Chapter 1 line 435: improper expression.

**Comment by DoongLi** [comment]
![1](https://github.com/user-attachments/assets/d8c6d511-961b-42dc-bcbd-e9a25f0e177a)
Chapter 1 line 395: ”沈绍杰“-“沈劭劼”

**Comment by yanyan-li** [comment]
感谢提出的问题，以修正
