### ISSUE TITLE
部分表达严谨性

### ISSUE THREAD

**Issue by HeadReaper-hc** [yanyan-li/SLAM-BOOK#3]
非常好的工作，目前只看了第一章。
1. P2-L107, 我不太清楚激光雷达中位姿估计有没有2d-2d,2d-3d,3d-3d这样的说法，更多的好像是scan-scan,scan-map这样的说法

2. P3-L139, IMU的中文直译应该是惯性测量单元吧

3. P3-L140, VINS改成VINS-Mono感觉更严谨一些， 然后预积分的频率应该是和图像频率是一致的，我不知道这算不算高频

除此以外，我觉得表达上还有很多可以改进的地方。

如果我说的有不对的地方，请作者自动忽略，会一直跟进这个项目， 作者加油。

**Comment by yanyan-li** [comment]
已经修改，感谢指正，感谢支持。
