### ISSUE TITLE
ASIFT引用问题

### ISSUE THREAD

**Issue by GRF-Sunomikp31** [yanyan-li/SLAM-BOOK#7]
原文： 因此 ASIFT 算4子 [22] 被设计出来解决大倾角图像的匹配问题。
[22]：Fully convolutional networks for semantic segmentation

这里ASITF引用paper是不是有点问题，ASIFT的paper是：ASIFT: A new framework for fully affine invariant image comparison

**Comment by yanyan-li** [comment]
谢谢纠正，ASIFT引用出了问题，我把它改正过来
